jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    script: |
      go get -v -t ./...
      go test -v  -timeout=5s -race ./...
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
    script: |
      go get -v -t ./...
      go test -v  -timeout=5s -race ./...
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    script: |
      go get -v -t ./...
      go test -v  -timeout=5s -race ./...
