resources:
  containers:
  - container: u14
    image: golang:1.11

  - container: u16
    image: golang:1.10

  - container: u18
    image: golang:1.9

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      ubuntu14:
        containerResource: u14
      ubuntu16:
        containerResource: u16
      ubuntu18:
        containerResource: u18

  container: $[ variables['containerResource'] ]

  steps:
    - script: |
        go get -u -t -v ./...
        go test -v ./...