jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: "go get -u -t -v ./...; go test -v ./..."
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
   - script: ./ci.sh
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
   - script: ./ci.sh
