

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      go get -u -t -v ./...
      go test -v ./...
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      go get -u -t -v ./...
      go test -v ./...
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      ruby 2.3:
        go_version: '1.9'
      ruby 2.4:
        go_version: '1.10'

  steps:
    - task: UseRubyVersion@0
      inputs:
        versionSpec: $(go_version)
    - script: |
        go get -u -t -v ./...
        go test -v ./...
